#! /bin/bash

gdown "https://drive.google.com/uc?id=1MndgLu6togwrlFGsPQ4TfVYMPaq97Kte" -O data.tar.gz
aunpack data.tar.gz
rm data.tar.gz
# jupyter lab extension for committing to github
jupyter lab build
#mkdir ~/.jupyter
#cp binder/.jupyter ~/
#cp binder/.jupyter/* /srv/conda/envs/notebook/etc/jupyter/
